#!/usr/bin/env node
/**
 * Bakes APP_ENV, APP_URL, and desktop build identity. Package hooks pass
 * --require-provenance so incomplete staging/production provenance fails closed.
 */

import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { resolveDesktopVersion } from './sync-version.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DESKTOP_ROOT = join(__dirname, '..');
const REPO_ROOT = join(DESKTOP_ROOT, '..', '..');
const FULL_SOURCE_REVISION = /^[0-9a-f]{40}$/;
const SEMVER = /^\d+\.\d+\.\d+$/;
const STAGING_SEMVER = /^\d+\.\d+\.\d+-staging\.[1-9]\d*\.[1-9]\d*$/;

function isVersionForChannel(channel, version) {
  return (channel === 'staging' ? STAGING_SEMVER : SEMVER).test(version);
}

export function resolveAppEnv(raw) {
  return raw === 'staging' || raw === 'local' ? raw : 'production';
}

export function resolveAppUrl(env, localUrl = process.env.ELECTRON_APP_URL) {
  if (env === 'staging') {
    return 'https://staging.jov.ie';
  }

  if (env === 'local') {
    // Match `dev:web:local` / apps/web/scripts/dev-fast.mjs (PORT || 3100).
    const candidate = localUrl || 'http://localhost:3100';
    let parsed;
    try {
      parsed = new URL(candidate);
    } catch {
      throw new Error(
        'ELECTRON_APP_URL for ELECTRON_ENV=local must be an http loopback URL.'
      );
    }
    // WHATWG URL keeps the brackets on IPv6 hostnames ('[::1]').
    const hostname = parsed.hostname.replace(/^\[|\]$/g, '');
    const isLoopback =
      hostname === 'localhost' ||
      hostname === '127.0.0.1' ||
      hostname === '::1';

    if (parsed.protocol !== 'http:' || !isLoopback) {
      throw new Error(
        'ELECTRON_APP_URL for ELECTRON_ENV=local must be an http loopback URL.'
      );
    }

    return parsed.origin;
  }

  return 'https://jov.ie';
}

function readVersion() {
  const version = readFileSync(join(REPO_ROOT, 'VERSION'), 'utf8').trim();
  if (!SEMVER.test(version)) {
    throw new Error(`VERSION file is not a valid semver string: "${version}"`);
  }
  return version;
}

export function resolveSourceRevision(env = process.env) {
  for (const candidate of [env.JOVIE_DESKTOP_SOURCE_REVISION, env.GITHUB_SHA]) {
    if (typeof candidate !== 'string') continue;
    const normalized = candidate.trim().toLowerCase();
    if (FULL_SOURCE_REVISION.test(normalized)) return normalized;
  }
  if (env.JOVIE_DESKTOP_DISABLE_GIT === '1') return null;
  try {
    const sha = execFileSync('git', ['rev-parse', 'HEAD'], {
      cwd: REPO_ROOT,
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'pipe'],
    })
      .trim()
      .toLowerCase();
    return FULL_SOURCE_REVISION.test(sha) ? sha : null;
  } catch {
    return null;
  }
}

export function resolveBuiltAt(channel, env = process.env) {
  if (channel === 'local') return null;
  const override = env.JOVIE_DESKTOP_BUILT_AT;
  if (typeof override === 'string' && override.trim().length > 0) {
    const parsed = Date.parse(override);
    if (!Number.isFinite(parsed)) {
      throw new Error(
        `JOVIE_DESKTOP_BUILT_AT must be an ISO-8601 timestamp: "${override}"`
      );
    }
    return new Date(parsed).toISOString();
  }
  return new Date().toISOString();
}

function renderEnvSource(appEnv, appUrl) {
  return `// AUTO-GENERATED by scripts/write-env.mjs — do not edit by hand.
// Re-generated on every \`predev\`, \`prebuild:staging\`, and \`prebuild:production\` run.
export const APP_ENV: 'production' | 'staging' | 'local' = '${appEnv}';
export const APP_URL = '${appUrl}';
`;
}

function renderIdentitySource(record) {
  return `// AUTO-GENERATED by scripts/write-env.mjs — do not edit by hand.
export const BAKED_DESKTOP_BUILD_IDENTITY = {
  channel: ${JSON.stringify(record.channel)},
  version: ${JSON.stringify(record.version)},
  sourceRevision: ${JSON.stringify(record.sourceRevision)},
  builtAt: ${JSON.stringify(record.builtAt)},
} as const;
`;
}

export function bakeDesktopEnvAndIdentity({
  env = process.env,
  requireProvenance = false,
} = {}) {
  const appEnv = resolveAppEnv(env.ELECTRON_ENV);
  const appUrl = resolveAppUrl(appEnv, env.ELECTRON_APP_URL);
  const version = resolveDesktopVersion({
    desktopVersion: env.DESKTOP_VERSION,
    electronEnv: appEnv,
    repoVersion: readVersion(),
  });
  const sourceRevision = resolveSourceRevision(env);
  const builtAt = resolveBuiltAt(appEnv, env);
  const identity = {
    channel: appEnv,
    version,
    sourceRevision,
    builtAt,
  };

  const complete =
    (identity.channel === 'production' || identity.channel === 'staging') &&
    isVersionForChannel(identity.channel, identity.version) &&
    typeof identity.sourceRevision === 'string' &&
    FULL_SOURCE_REVISION.test(identity.sourceRevision) &&
    typeof identity.builtAt === 'string' &&
    Number.isFinite(Date.parse(identity.builtAt));
  if (requireProvenance && !complete) {
    throw new Error(
      '[write-env] Packaged production/staging provenance is unavailable or incomplete. Refusing to label an unverifiable desktop binary as a release build.'
    );
  }

  writeFileSync(
    join(DESKTOP_ROOT, 'src', 'env.generated.ts'),
    renderEnvSource(appEnv, appUrl)
  );
  writeFileSync(
    join(DESKTOP_ROOT, 'src', 'build-identity.generated.ts'),
    renderIdentitySource(identity)
  );
  writeFileSync(
    join(DESKTOP_ROOT, 'build', 'build-identity.json'),
    `${JSON.stringify(identity)}\n`
  );

  return { appEnv, appUrl, identity };
}

function isMainModule() {
  try {
    return import.meta.url === pathToFileURL(process.argv[1]).href;
  } catch {
    return true;
  }
}

if (isMainModule()) {
  try {
    const requireProvenance = process.argv.includes('--require-provenance');
    const result = bakeDesktopEnvAndIdentity({ requireProvenance });
    console.log(
      `[write-env] Wrote APP_ENV='${result.appEnv}' APP_URL='${result.appUrl}' to src/env.generated.ts`
    );
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    process.exit(1);
  }
}
